
const R = require('ramda');


let prvySetOtazok = ["Would you rather Have a dog with a cat’s personality or a cat with a dog’s personality?",
  "If you were reborn in a new life, would you rather be alive in the past or future?",
  "Would you rather eat no candy at Halloween or no turkey at Thanksgiving?",
  "Would you rather date someone you love or date someone who loves you?",
  "Would you rather lose the ability to lie or believe everything you’re told?",
  "Would you rather be free or be totally safe?",
  "Would you rather Eat shit that tasted like chocolate, or eat chocolate that tasted like crap?",
  "Would you rather Look 10 years older from the neck up, or the neck down?",
  "Would you rather Be extremely underweight or extremely overweight?",
  "Would you rather Experience the beginning of planet earth or the end of planet earth?",
  "Would you rather have an incredibly annoying high-pitched voice or a really deep manly voice?",
  "Would you rather have a full-blown moustache for a year or permanently hairy legs for ten years?",
  "Would you rather give up your phone or only wear Crocs for the rest of your life?",
  "Would you rather clog the toilet on a first date or first day at a new job?",
  "Would you rather have an abnormally big toe or an abnormally big ear?",
  "Would you rather be three feet tall or eight feet tall?",
  "Would you rather have to be naked at work for an hour or be dropped off two miles from your house whilst you're naked and you have to try and get home?",
  "Would you rather smell like cheese (which has been left in the sun) or a hamster cage (which hasn't been cleaned for a fortnight)?",
  "Would you rather be a mad genius or popular but dim?",
  "Would you rather a nose that never stops growing or ears that never stop growing?",
  "Would you rather whip or be whipped?",
  "Would you rather have your hair pulled or your back scratched?",
  "Would you rather dominate or be dominated?",
  "Would you rather have a cupboard full of sex toys or kinky outfits?",
  "Would you rather sleep with someone on the first date or wait for six months?",
  "Would you rather have unbelievable sex that lasts ten minutes or average sex that lasts an hour?",
  "Would you rather your partner be kinky or romantic?",
  "Would you rather swallow or spit?",
  "Would you rather have sex with the light on or the light off?",
  "Would you rather have sex in the shower or on the kitchen table?",
  "Would you rather accidentally send a naughty picture to your dad or your boss?",
  "Would you rather give up sex or give up food?",
  "Would you rather walk in on your parents having sex or have them walk in on you having sex?",
  "Would you rather be stuck in a phone box with ten snakes or ten tarantulas?",
  "Would you rather say your ex's name during sex or your partner's best friend's name?",
  "Would you rather have the face of a pensioner but the body of a twenty-year-old or the body of a pensioner and the face of a twenty-year-old?",
  "Would you rather be funny but really stupid or boring but really smart?",
  "Would you rather be famous or rich?",
  "Would you rather find the love of your life or find a million pounds?",
  "Would you rather be able to travel everywhere for free or eat everywhere for free?",
  "Would you rather have arms as long as Mr. Tickle or legs as short as E.T?",
  "Would you rather empty a swimming pool using just a fork or get in a swimming pool for half an hour with a jellyfish?",
  "Would you rather drink soup out of a farmer's welly or from a binman's sock?",
  "Would you rather have no sense of smell or no sense of taste?",
  "Would you rather have your name tattooed on your forehead or have no front teeth?"];

  const druhySetOtazok = [ " Would you rather End death due to car accidents or end terrorism?",
" Would you rather Leave your unemployed son homeless or pay for his drug habits and illegal activities?",
" Would you rather End the life a single human being or 100 cute baby animals?",
" Would you rather End hunger or end your hunger?",
" Would you rather Skinny dip with your classmate or with a stranger?",
" Would you rather give up your love life or work life?",
" Would you rather live in an amusement park or a zoo?",
" Would you rather be a millionaire by winning the lottery or by working 100 hours a week?",
" Would you rather read minds or accurately predict future?",
" Would you rather eat only pizza for 1 year or eat no pizza for 1 year?",
" Would you rather visit 100 years in the past or 100 years in the future?",
" Would you rather Be able to choose your bridesmaid dress or never have to be a bridesmaid again?",
" Would you rather Have your gynecologist use a speculum that is too large or a speculum that is cold?",
" Would you rather Have girl’s night with Oprah Winfrey or Hillary Clinton?",
" Would you rather Have painful cramps again or never have to shave again?",
" Would you rather Be catcalled or be treated like a human being?",
" Would you rather Go through a whole day with a very visible panty line or with lipstick on your teeth?",
" Would you rather Be asked if you are PMSing every single day or be told to stop being so sensitive every day?",
" Would you rather Wear a push-up bra all day long or stiletto heels all day long?",
" Would you rather Have an entire eyebrow accidentally waxed off or Get a rash from a poor bikini wax job?",
" Would you rather Get your period at the beach or on a date?",
" Would you rather Live in a world without the movie “Bridesmaids” or without “Mean Girls”?",
" Would you rather Have an awful hair day or go through the whole day with your bra’s underwire poking you?",
" Would you rather Have tampons for fingers or have pubic hair for teeth.",
" Would you rather love your spouse or be loved by your spouse?",
" Would you rather make out on your first date or wait for the right time?",
" Would you rather have physical intimacy or no true love?",
" Would you rather have large assets and a disfigured body or have smaller assets with a fantastic body?",
" Would you rather not put makeup again or not look at yourself again?",
" Would you rather have your menstrual cycle on your first night or your honeymoon?",
" Would you rather get with your boss to get promoted or give up the promotion?",
" Would you rather be the subject matter of gossip or never being talked about at all?",
" Would you rather be married to someone extremely attractive or be someone who is extremely attractive?",
" Would you rather Have one partner or multiple partners? Would you rather Talk with me about someone you fancy or fantasize about it secretly in your mind?",
" Would you rather Watch a girl on girl or guy on guy video, to turn yourself on?",
" Would you rather Watch something erotic with me, or read an erotica loud, while touching me?",
" Would you rather Have it with the lights on or off?",
" Would you rather Pay for having sex, or get paid for it?",
" Would you rather have sex with my best friend, or with your best friend?",
" Would you rather Swallow or spit?",
" Would you rather Be on top or underneath?",
" Would you rather Have sex with someone or watch someone having it?",
" Would you rather Have sex in the morning or at night?",
" Would you rather Bring another person in bed or cheat on me?",
" Would you rather Receive an oral or give one?",
" Would you rather do romantic things or try out some new kinky ideas?",
" Would you rather End a first date with sex or with a passionate kiss?",
" Would you rather be caught cheating or catch your spouse cheating?",
" Would you rather let your significant other sleep with your best friend or sleep with your significant other’s best friend?",
" Would you rather let your spouse date your best friend or your arch enemy?",
" Would you rather confess your crimes in front of your children or commit the crime in front of your children?",
" Would you rather Kiss or girl or be kissed by a girl? Would you rather Have a long-term relationship or flings?",
" Would you rather Have an average girl with a great personality or a hot girl?",
" Would you rather Stay in or go out for a date?",
" Would you rather Check out a girl from the back or the front?",
" Would you rather Wear comfortable clothes or fashionable clothes?",
" Would you rather Go to a bar, a club, a house party, or just stay home?",
" Would you rather Find true love or be rich?",
" Would you rather See a girl in shorts, or in a skirt?",
" Would you rather Spend $5,000 on traveling or on a physical item like a TV?",
" Would you rather Not brush your teeth for ten days or not shower for ten days?",
" Would you rather Kiss a girl on the first date or wait?",
" Would you rather Be a tutor for underprivileged kids or volunteer at a homeless shelter or Would you rather Date me or be my friend?",
" Would you rather Go to an expensive restaurant or a cheaper relaxed atmosphere where the food is equally good?",
" Would you rather weave a web of lies for your girlfriend or tell her the whole truth?",
" Would you rather continue your relationship or leave if you find your girlfriend is diagnosed with a terminally fatal disease?",
" Would you rather eat the food prepared by your mom or your girlfriend?",
" Would you rather take your girlfriend out for a date or snuggle her in your arms and stay indoors?",
" Would you rather see your girlfriend with or without makeup?",
" Would you rather leave your girlfriend if she is not good in bed or continue living with her?",
" Would you rather sleep with your girlfriend or get paid $10000 not to?",
" Would you rather have an obsessed girlfriend or a hot, cheating one?",
" Would you rather Be poor and good looking or wealthy and ugly?  Would you rather Be hairy or completely bald?",
" Would you rather Be 140cm or 300cm?"];

const stvrtySetOtazok = [
    " Would you rather Be blind or deaf?",
" Would you rather Be short and well built or tall and fat?",
" Would you rather Take a guaranteed $100,000 or a 50/50 chance at $1,000,000?",
" Would you rather Eat healthily or exercise regularly?",
" Would you rather Be super strong or super fast?",
" Would you rather Be poor and find true love or be rich?",
" Would you rather Lose half your hair or lose half your hearing?",
" Would you rather Work hard at the job you love or slack off at a boring job?",
" Would you rather Look weak and be strong or look strong and be weak?",
" Would you rather Have a third wrist or a third eye?",
" Would you rather Be as wide as you are tall, or as tall as you are wide?",
" Would you rather Age from the neck up or the neck down only?",
" Would you rather join the army or be an athlete?",
" Would you rather go on a free, fully paid dream vacation or be with someone you love in your home?",
" Would you rather be the richest person in the World or the smartest?",
" Would you rather own your dream car or have never-ending knowledge?",
" Would you rather create history or delete it?",
" Would you rather have a high profile job with no family for life or an average job with a family to live by?",
" Would you rather have a crush on ugly people or have ugly people have a crush on you?",
" Would you rather grab the front or the back of a girl when invisible?",
" Would you rather Be a cow or a chicken?",
" Would you rather have no taste buds or be color blind?",
" Would you rather Eat everything you see or lick everything you see?",
" Would you rather Have a foot long nose or a foot long tongue?",
" Would you rather Have a baby at 10 or a baby at 60?",
" Would you rather Be in jail for ten years or be in the coma for 20 years?",
" Would you rather Have no brother or no sister?",
" Would you rather Be invisible or be fast?",
" Would you rather Look like a fish or smell like a fish?",
" Would you rather Play on Minecraft or play FIFA?",
" Would you rather Fight 100 duck-sized horses or 1 horse-sized duck?",
" Would you rather Have a grapefruit-sized head or a head the size of a watermelon?",
" Would you rather Be a tree or have to live in a tree for the rest of your life?",
" Would you rather Live in space or under the sea?",
" Would you rather lose your sense of touch or your sense of smell?",
" Would you rather be Donald Trump or George Bush?",
" Would you rather Have no hair or be completely hairy?",
" Would you rather wake up in the morning looking like a giraffe or a kangaroo?",
" Would you rather have a booger hanging from your nose for the rest of your life or earwax planted on your earlobes?",
" Would you rather Have a sumo wrestler on top of you or yourself on top of him?",
" Would you rather Stop using YouTube or stop using Instagram?  Would you rather Check your email first every morning or Check your social networks first every morning?",
" Would you rather Lose your keys or forget your cell phone?",
" Would you rather Only have access to YouTube on the Internet or only have access to games on the Internet?",
" Would you rather Eat the same food for the rest of your life or never use Instagram again?",
" Would you rather Watch TV all the time or not watch TV at all?",
" Would you rather Have slow but unlimited internet or Paid but Limited Internet?",
" Would you rather Give up shopping for three or give up emoji for three months?",
" Would you rather Lose all your contacts or lose $100?",
" Would you rather Eat an entire stick of butter or send an embarrassing email to your entire company?",
" Would you rather Be stung by a jellyfish or give up Facebook for a week?",
" Would you rather Never have internet access or be a professional clown?",
" Would you rather Create a super successful app or go on tour with Beyoncé?",
" Would you rather Not use email for a week or feel hungover for a week?",
" Would you rather have an iPod fitted in your mind and listen to any music of your choice, anytime or watch your dreams alive on television?",
" Would you rather give up search engines or social media applications?",
" Would you rather play you in Minecraft or Super Mario?",
" Would you rather have a lifelong free subscription of iTunes or App Store?",
" Would you rather have free internet for life or free food?",
" Would you rather live without a cell phone or news?",
" Would you rather have your brain transplanted into a robot or an animal of your choice?",
" Would you rather infinite battery life for your cell phone or infinite fuel for your car?",
" Would you rather burn all your books or buy a Kindle or an eBook reader?",
" Would you rather surf the internet or shop till you drop?",
" Would you rather give up your snazzy home theater or your PlayStation?"
];

  const tretiSetOtazok = ["Would you rather never receive oral again or never smoke weed again?",
"Would you rather send nudes to your boss or to your parents?",
"Would you rather sneeze every time you orgasm, or orgasm every time you sneeze?",
"Would you rather spit or swallow?",
"Would you rather only be able to be on the bottom during sex, or only on the top? ",
"Would you rather be cheated on by a partner, or cheat on a partner?",
"Would you would rather get spanked or do the spanking?",
"Would you rather never wear underwear again or never wear socks again?",
"Would you rather walk in on your parents having sex or have your parents walk in on you having sex?"
];

  const mLTdirty = [
    " Who’s most likely to have sex with a stranger?",
    " Who’s most likely to ask their friends a bunch of stupid questions?",
    " Who’s most likely to get caught having sex in a dressing room?",
    " Who’s most likely to get caught having sex at work?",
    " Who’s most likely to get back together with their ex?",
    " Who’s most likely to tell a lie just for the fun of it?",
    " Who’s most likely to become a billionaire dom/domme?",
    " Who’s most likely to urinate in a swimming pool and get caught?",
    " Who’s most likely to prank call a stranger?",
    " Who’s most likely to score with their college professor?",
    " Who’s most likely to have a one night stand and forget the person’s name?",
    " Who’s most likely to have a secret porn addiction?",
    " Who’s most likely to get drunk and have a one night stand?",
    " Who’s most likely to get a face tattoo?",
    " Who’s most likely to get a genital tattoo?",
    " Who’s most likely to try the entire Kama Sutra",
    " Who’s most likely to become an amateur porn star?",
    " Who’s most likely to convert to another religion just to have sex with someone?",
    " Who’s most likely to have a threesome?",
    " Who’s most likely to get busted by cops while with prostitutes?",
    " Who’s most likely to get married and divorced 10 times?",
    " Who’s most likely to become a meth head?",
    " Who’s most likely to cosplay as a Power Puff Girl?",
    " Who’s most likely to have sex with an octogenarian (80-89 years old)?",
    " Who’s most likely to get fired at work for looking at porn?",
    " Who’s most likely to get breast implants or a penis implant?",
    " Who’s most likely to have a Viagra prescription?",
    " Who’s most likely to have a baby and not even realize they’re pregnant?",
    " Who’s most likely to ruin a threesome because of making stupid comments?",
    " Who’s most likely to end up homeless?",
    " Who’s most likely to change their sex?",
    " Who’s most likely to actually be really sexy as an opposite gender?",
    " Who’s most likely to cheat on their significant other with a midget?",
    " Who’s most likely to trade sex for rent money?",
    " Who’s most likely to have a weird and disturbing sexual fetish?",
    " Who’s most likely to go to jail for conspiracy to commit murder?",
    " Who’s most likely to go to jail for indecent exposure?",
    " Who’s most likely to go to jail for annoying a police officer?",
    " Who’s most likely to try to score at someone’s funeral?",
    " Who’s most likely to become a famous meme?",
    " Who’s most likely to hypnotize someone just for sex?",
    " Who’s most likely to sleep with Andy Dick?",
    " Who’s most likely to confess all their sexual wins to a priest?",
    " Who’s most likely to sleep with a total loser out of pure desperation?",
    " Who’s most likely to be shy on the outside but a total perv behind closed doors?",
    " Who’s most likely to leave their spouse for someone they met playing Fortnite?",
    " Who’s most likely to have a sex doll in their closet?",
    " Who’s most likely to get caught trying to join the mile high club?",
    " Who’s most likely to try to score with their best friend’s mom or dad?",
    " Who’s most likely to father or mother nine children?",
    " Who’s most likely to get banned from Facebook?",
    " Who’s most likely to join a weird sex cult and then say, “It’s not a cult!”",
    " Who’s most likely to get cheated on?",
    " Who’s most likely to have to go to the ER for an embarrassing sex toy mishap?",
    " Who’s most likely to get rejected by a prostitute?"
  ];

  const tagFriend1 = [
    "Do you often watch TV?",
    "What program do you prefer to watch?",
    "What’s your favorite TV show?",
    "Can you laugh with a series?",
    "Would you dare to report on the quiz?",
    "What’s your favorite kind of sandwich?",
    "Whether you prefer to go to the cinema or watch movies at home?",
    "Did you read any good book lately?",
    "Is there soon some concert to which you like to go?",
    "Do you dance on outings or parties?",
    "Are you watching the news?",
    "What is your ideal car?",
    "What is your dream job?",
    "Which three places would like to visit?",
    "What is your favorite season?",
    "Did you try the Mexican (Japanese or Chinese) food?",
    "Do you have a pet?",
    "Do you remember your favorite subjects and teachers from the school?",
    "What are your favorite foods and dishes?",
    "Do you like to cook?",
    "Do you often visit restaurants?",
    "Do you surf the internet often?",
    "Where would you like to live?",
    "Where does your perfect holiday pass?",
    "Can you describe your bedroom?",
    "What historical person would you like to interview?",
    "What are your three favorite band’s musicians?",
    "What kind of clothing would you not put under any circumstances?",
    "What is freedom according to you?",
    "What is your favorite book?",
    "Do you often think about what happens to you and what you feel?",
    "What super power would you like to have?",
    "What four series are your favorites?",
    "What three things you appreciate most about some person?",
    "How would you like to be in the future?",
    "If you were an animal, what would you be?",
    "If you could travel anywhere in the world where would you go? why?",
    "What song would serve to summarize your personality? Why?",
    "How would you describe your friends?",
    "What three types of job you would like to exercise?",
    "What ability would you like to improve to become fully mastered?",
    "If you could only keep five phone numbers of people outside your family, what would they be?",
    "What kind of person would you be afraid of?",
    "What is the craziest you’ve done?",
    "If you won the lottery? What is the first thing you would buy?",
    "On what topic you would like for people to ask you, to know you better?",
    "Do you wear/lose an umbrella?",
    "Do you remember your dreams in the morning?",
    "What is the most interesting story from your childhood?",
    "What year was your happiest and why?",
    "Do you like brownies and chocolate?",
    "Do you prefer rainy or snowy days?",
    "When is your birthday?",
    "Do you have a profile on Facebook or another social network?",
    "Would you deal with extreme sports, for example, bungee jump?"
  ];

function getOtazky(nazov){

  switch (nazov) {
    case 'prvySetOtazok':
      let kopia = R.clone(prvySetOtazok);
        return kopia;
      break;
    case 'druhySetOtazok':
        return druhySetOtazok;
      break;
    case 'tretiSetOtazok':
        return tretiSetOtazok;
      break;
    case 'stvrtySetOtazok':
      return stvrtySetOtazok;
      break;
    case 'mLTdirty':
      return mLTdirty;
      break;
    case 'tagFriend1':
      return tagFriend1;
      break;
    case 'childrenMegapackWouldYouRather':
      return childrenMegapackWouldYouRather;
      break;

    default:
      return "Ups. Niekde nastala chyba."

  }

}


module.exports = getOtazky;

const truthOrDare1 = [];

const childrenMegapackWouldYouRather = [" Would you rather be a detective or a pilot?",
  " Would you rather go skiing or go to a water park?",
  " Would you rather fly a kite or swing on a swing?",
  " Would you rather dance or sing?",
  " Would you rather play hide and seek or dodgeball?",
  " Would you rather be incredibly funny or incredibly smart?",
  " Would you rather become five years older or two years younger?",
  " Would you rather have a full suit of armor or a horse?",
  " Would you rather be a master at drawing or be an amazing singer?",
  " Would you rather be a wizard or a superhero?",
  " Would you rather sail a boat or ride in a hang glider?",
  " Would you rather brush your teeth with soap or drink sour milk?",
  " Would you rather be a famous inventor or a famous writer?",
  " Would you rather do school work as a group or by yourself?",
  " Would you rather be able to do flips and backflips or break dance?",
  " Would you rather see a firework display or a circus performance?",
  " Would you rather it be warm and raining or cold and snowing today?",
  " Would you rather be able to create a new holiday or create a new sport?",
  " Would you rather only be able to walk on all fours or only be able to walk sideways like a crab?",
  " Would you rather start a colony on another planet or be the leader of a small country on Earth?",
  " Would you rather be able to see things that are very far away, like binoculars or be able to see things very close up, like a microscope?",
  " Would you rather be an incredibly fast swimmer or an incredibly fast runner?",
  " Would you rather own an old-timey pirate ship and crew or a private jet with a pilot and infinite fuel?",
  " Would you rather be able to jump as far as a kangaroo or hold your breath as long as a whale?",
  " Would you rather be able to type/text very fast or be able to read really quickly?",
  " Would you rather randomly turn into a frog for a day once a month or randomly turn into a bird for a day once every week?",
  " Would you rather have the chance to design a new toy or create a new TV show?",
  " Would you rather be really good at math or really good at sports?",
  " Would you rather be the author of a popular book or a musician in a band who released a popular album?",
  " Would you rather live in a house shaped like a circle or a house shaped like a triangle?",
  " Would you rather live in a place with a lot of trees or live in a place near the ocean?",
  " Would you rather have your room redecorated however you want or ten toys of your choice (can be any price)?",
  " Would you rather have a magic carpet that flies or a see-through submarine?",
  " Would you rather everything in your house be one color or every single wall and door be a different color?",
  " Would you rather visit the international space station for a week or stay in an underwater hotel for a week?",
  " Would you rather have ninja-like skills or have amazing coding skills in any language?",
  " Would you rather be able to control fire or water?",
  " Would you rather have a new silly hat appear in your closet every morning or a new pair of shoes appear in your closet once a week?",
  " Would you rather be able to remember everything you’ve ever seen or heard or be able to perfectly imitate any voice you heard?",
  " Would you rather drink every meal as a smoothie or never be able to eat food that has been cooked?",
  " Would you rather meet your favorite celebrity or be on a TV show?",
  " Would you rather be a master at origami or a master of sleight of hand magic?",
  " Would you rather have a tail that can’t grab things or wings that can’t fly?",
  " Would you rather have a special room you could fill with as many bubbles as you want, anytime you want or have a slide that goes from your roof to the ground?",
  " Would you rather dance in front of 1000 people or sing in front of 1000 people?",
  " Would you rather ride a very big horse or a very small pony?",
  " Would you rather be able to shrink down to the size of an ant any time you wanted to or be able to grow to the size of a two-story building anytime you wanted to?",
  " Would you rather be able to move silently or have an incredibly loud and scary voice?",
  " Would you rather be bulletproof or be able to survive falls from any height?",
  " Would you rather eat a whole raw onion or a whole lemon?",
  " Would you rather be incredibly luck with average intelligence or incredibly smart with average luck?",
  " Would you rather be able to change color to camouflage yourself or grow fifteen feet taller and shrink back down whenever you wanted?",
  " Would you rather instantly become a grown up or stay the age you are now for another two years?",
  " Would you rather have a personal life-sized robot or a jetpack?",
  " Would you rather never have any homework or be paid 10$ per hour for doing your homework?",
  " Would you rather take a coding class or an art class?",
  " Would you rather eat a bowl of spaghetti noodles without sauce or a bowl of spaghetti sauce without noodles?",
  " Would you rather have eyes that change color depending on your mood or hair that changes color depending on the temperature?",
  " Would you rather eat an apple or an orange?",
  " Would you rather taste the best pizza that has ever existed once but never again or have the 4th best pizza restaurant in the world within delivery distance?",
  " Would you rather go snorkeling on a reef or camping by a lake?",
  " Would you rather have an elephant-sized cat or a cat-sized elephant?",
  " Would you rather be able to jump into any picture and instantly be in that place and time but able to return or would you rather be able to take pictures of the future, just stand in a place think of a time in the future and take a picture?",
  " Would you rather play outdoors or indoors?",
  " Would you rather eat broccoli flavored ice cream or meat flavored cookies?",
  " Would you rather eat one live nonpoisonous spider or have fifty nonpoisonous spiders crawl on you all at once?",
  " Would you rather live on a sailboat or in a cabin deep in the woods?",
  " Would you rather have an amazing tree house with slides and three rooms or an amazing entertainment system with a huge TV and every game console?",
  " Would you rather eat a popsicle or a cupcake?",
  " Would you rather own a hot air balloon or an airboat?",
  " Would you rather have a bubble gun that shoots giant 5-foot bubbles or a bathtub-sized pile of Legos?",
  " Would you rather eat a worm or a grasshopper?",
  " Would you rather have super strength or super speed?",
  " Would you rather never eat cheese again or never drink anything sweet again?",
  " Would you rather have your very own house next to your parent’s house or live with your parents in a house that’s twice the size of the one you live in now?",
  " Would you rather have a cupcake or a piece of cake?",
  " Would you rather be able to move wires around with your mind or be able to turn any carpeted floor into a six-foot deep pool of water?",
  " Would you rather be able to speak any language but not be able to read in any of them or read any language but not be able to speak any of them?",
  " Would you rather live in a house where all the walls were made of glass or live in an underground house?",
  " Would you rather stay a kid until you turn 80 or instantly turn 40?",
  " Would you rather be able to watch any movies you want a week before they are released or always know what will be trendy before it becomes a trend?",
  " Would you rather be an athlete in the Summer Olympics or the Winter Olympics?",
  " Would you rather be fluent in 10 languages or be able to code in 10 different programming languages?",
  " Would you rather drive a police car or an ambulance?",
  " Would you rather have a piggy bank that doubles any money you put in it or find ten dollars under your pillow every time you wake up?",
  " Would you rather own a mouse or a rat?",
  " Would you rather live in a cave or a tree house?",
  " Would you rather do a book report or a science project for a school assignment?",
  " Would you rather fly an airplane or drive a fire truck?",
  " Would you rather be a talented engineer or a talented coder?",
  " Would you rather spend the whole day in a huge garden or spend the whole day in a large museum?",
  " Would you rather be able to find anything that was lost or every time you touched someone they would be unable to lie?",
  " Would you rather be a babysitter or a dog sitter?",
  " Would you rather ride a bike or ride a kick scooter?",
  " Would you rather work alone on a school project or work with others on a school project?",
  " Would you rather open one 5$ present every day or one big present that costs between 100$ to 300$ once a month?",
  " Would you rather have an unlimited supply of ice cream or a popular ice cream flavor named after you?",
  " Would you rather live in a place that is always dusty or always humid?",
  " Would you rather have any book you wanted for free or be able to watch any movie you wanted for free?",
  " Would you rather be able to play the piano or the guitar?",
  " Would you rather be able to read lips or know sign language?",
  " Would you rather eat a hamburger or a hot dog?",
  " Would you rather ride a roller coaster or see a movie?",
  " Would you rather be able to change the color of anything with just a thought or know every language that has ever been spoken on Earth?",
  " Would you rather have super strong arms or super strong legs?",
  " Would you rather move to a different city or move to a different country?",
  " Would you rather be wildly popular on the social media platform of your choice or have an extremely popular podcast?",
  " Would you rather be able to talk to animals and have them understand you, but you can’t understand them, or would you rather be able to understand what animals say but they can’t understand you?",
  " Would you rather eat smores or cupcakes?",
  " Would you rather ride in a hang glider or ride in a helicopter?",
  " Would you rather never have to sleep or never have to eat?",
  " Would you rather be an amazing photographer or an amazing writer?",
  " Would you rather sneeze uncontrollably for 15 minutes once every day or sneeze once every 3 minutes of the day while you are awake?",
  " Would you rather be able to remember everything in every book you read or remember every conversation you have?",
  " Would you rather have 10 mosquito bites or 1 bee sting?",
  " Would you rather be an actor/actress in a movie or write a movie script that would be made into a movie?",
  " Would you rather be able to talk to dogs or cats?",
  " Would you rather have a jetpack or a jet?",
  " Would you rather ride a roller coaster or go down a giant water slide?",
  " Would you rather get every Lego set that comes out for free or every new video game system that comes out for free?",
  " Would you rather go on vacation to a new country every summer vacation or get an extra three weeks of summer break?",
  " Would you rather eat a turkey sandwich with vanilla ice cream inside or eat vanilla ice cream with bits of turkey inside?",
  " Would you rather ride a skateboard or a bike?",
  " Would you rather visit every country in the World or be able to play any musical instrument?",
  " Would you rather control the outcome of any coin flip or be unbeatable at rock, paper, scissors?",
  " Would you rather be able to type faster than anyone or speak faster than anyone?",
  " Would you rather have a private movie theater or your own private arcade?",
  " Would you rather be a cyborg or a robot?",
  " Would you rather ride in a hang glider or skydive?",
  " Would you rather every vegetable you eat taste like candy but still be healthy or all water you drink taste like a different delicious beverage every time you drink it?",
  " Would you rather be really good at skateboarding or really good at any video game you tried?",
  " Would you rather lay in a bathtub filled with worms for 5 minutes or lay in a bathtub filled with beetles that don’t bite for 5 minutes?",
  " Would you rather live next to a theme park or next to a zoo?",
  " Would you rather have a room with whiteboard walls that you can draw on or a room where the whole ceiling is one big skylight?",
  " Would you rather have a house with trampoline floors or a house with aquarium floors?",
  " Would you rather live in a castle or a spaceship traveling far from earth?",
  " Would you rather play soccer or baseball?",
  " Would you rather ride a camel or ride a horse?",
  " Would you rather be amazing at drawing and painting or be able to remember everything you ever read?",
  " Would you rather have a jetpack or a hoverboard that actually hovers (no wheels)?",
  " Would you rather have a ten dollar bill or ten dollars in coins?",
  " Would you rather get up early or stay up late?",
  " Would you rather be able to eat any spicy food without a problem or never be bitten by another mosquito?",
  " Would you rather never have to take a bath/shower but still always smell nice or never have to get another shot but still be healthy?",
  " Would you rather be able to learn everything in a book by putting it under your pillow while you slept or be able to control your dreams every night?",
  " Would you rather be able to see new colors that no other people could see or be able to hear things that no other humans can hear?",
  " Would you rather move to a country and city of your choice or stay in your own country but not be able to decide where you moved?",
  " Would you rather have pancakes every day for breakfast or pizza every day for dinner?",
  " Would you rather drive a race car or fly a helicopter?",
  " Would you rather be unable to control how fast you talk or unable to control how loud you talk?",
  " Would you rather be rich and unknown or be famous and have enough money, but not be rich?",
  " Would you rather live in a house in the forest where there aren’t many people around or live in a city with lots of people around?",
  " Would you rather dance or draw?",
  " Would you rather have a 3d printer or the best phone on the market?",
  " Would you rather go snow skiing or water skiing?",
  " Would you rather never be able to eat any type meat again or never be able to eat things with sugar in them?",
  " Would you rather have no homework or no tests?",
  " Would you rather be able to control the length of your hair with your mind or be able to control the length of your fingernails with your mind? (Hair and nails grow/shrink about 1 inch in 10 seconds",
  " Would you rather get to name a newly discovered tree or a newly discovered spider?",
  " Would you rather swim in Jell-O or swim in Nutella?",
  " Would you rather play on swings or play on a slide?",
  " Would you rather have the power to shrink things to half their size or the power to enlarge things to twice their size?",
  " Would you rather live in a base under the ocean or a floating base in the sky?",
  " Would you rather not need to eat and never be hungry or not need to drink and never be thirsty?",
  " Would you rather be the fastest kid at your school or the smartest kid at your school?",
  " Would you rather be a scientist or be the boss of a company?",
  " Would you rather have a magic freezer that always has all your favorite ice cream flavors or one that has a different ice cream flavor every time you open the door?",
  " Would you rather have a very powerful telescope or a very powerful microscope?",
  " Would you rather hang out for an hour with 10 puppies or 10 kittens?",
  " Would you rather be able to change colors like a chameleon or hold your breath underwater for an hour?",
  " Would you rather learn to surf or learn to ride a skateboard?",
  " Would you rather eat your favorite food every day or find 5 dollars under your pillow every morning?",
  " Would you rather have a pet penguin or a pet Komodo dragon?",
  " Would you rather be able to eat pancakes as much as you want without it hurting your health or be able to eat as much bacon as you want without it hurting your health?",
  " Would you rather be able to talk to animals or be able to fly?",
  " Would you rather own a restaurant or be a chef?",
  " Would you rather have a pet dinosaur of your choosing or a dragon the size of a dog?",
  " Would you rather have an amazing tree house or your whole yard be a trampoline?",
  " Would you rather have a slide that goes from your home’s roof to the ground or be able to change and control what color the lights are in your home?",
  " Would you rather be a famous musician or a famous business owner?",
  " Would you rather play in a giant mud puddle or a pool?",
  " Would you rather have your favorite artist perform a private show just for you or perform on stage next to your favorite artist for thousands of people?",
  " Would you rather be too hot or too cold?",
  " Would you rather have 100$ now or 1000$ in a year?",
  " Would you rather have a real triceratops or a robot triceratops? (Both are the same size",
  " Would you rather have everything you draw become real or become a superhero of your choice?",
  " Would you rather be given every Lego set that was ever made or get every new Lego set that comes out for free?",
  " Would you rather go to the beach or go to the zoo?",
  " Would you rather get a new pair of shoes or a jacket?",
  " Would you rather read a book or read a magazine?",
  " Would you rather be the fastest swimmer on earth or the third fastest runner on earth?",
  " Would you rather drink orange juice or milk?",
  " Would you rather go camping or stay in a hotel room?",
  " Would you rather go to the doctor for a shot or the dentist to get a cavity filled?",
  " Would you rather be able to make plants grow very quickly or be able to make it rain whenever you wanted?",
  " Would you rather be a falcon or a dolphin?",
  " Would you rather be able to read minds or see one day into the future?",
  " Would you rather have fireworks go off every evening for an hour or have Christmas three times a year?",
  " Would you rather eat a bowl of spaghetti that was just one long noodle or eat ice cream launched from a catapult?",
  " Would you rather watch a two-hour movie or watch two hours of shows?"
];